---
kind: pipeline
name: testing
steps:
- name: test-vet
  image: golang:1.12
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
  commands:
    - go vet
  when:
    event:
    - push
    - pull_request

- name: test-sqlite
  image: golang:1.12
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_CACHE_ENABLE: false
  commands:
  - make test-sqlite
  when:
    event:
    - push
    - pull_request

- name: test-sqlite-cache
  image: golang:1.12
  depends_on:
    - test-sqlite
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_CACHE_ENABLE: true
  commands:
  - make test-sqlite
  when:
    event:
    - push
    - pull_request

- name: test-mysql
  image: golang:1.12
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_MYSQL_HOST: mysql
    TEST_MYSQL_CHARSET: utf8
    TEST_MYSQL_DBNAME: xorm_test
    TEST_MYSQL_USERNAME: root
    TEST_MYSQL_PASSWORD:
    TEST_CACHE_ENABLE: false
  commands:
  - make test-mysql
  when:
    event:
    - push
    - pull_request

- name: test-mysql-cache
  image: golang:1.12
  depends_on:
    - test-mysql
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_MYSQL_HOST: mysql
    TEST_MYSQL_CHARSET: utf8
    TEST_MYSQL_DBNAME: xorm_test
    TEST_MYSQL_USERNAME: root
    TEST_MYSQL_PASSWORD:
    TEST_CACHE_ENABLE: true
  commands:
  - make test-mysql
  when:
    event:
    - push
    - pull_request

- name: test-mysql-utf8mb4
  image: golang:1.12
  depends_on:
    - test-mysql-cache
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_MYSQL_HOST: mysql
    TEST_MYSQL_CHARSET: utf8mb4
    TEST_MYSQL_DBNAME: xorm_test
    TEST_MYSQL_USERNAME: root
    TEST_MYSQL_PASSWORD:
    TEST_CACHE_ENABLE: false
  commands:
  - make test-mysql
  when:
    event:
    - push
    - pull_request

- name: test-mysql-utf8mb4-cache
  image: golang:1.12
  depends_on:
    - test-mysql-utf8mb4
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_MYSQL_HOST: mysql
    TEST_MYSQL_CHARSET: utf8mb4
    TEST_MYSQL_DBNAME: xorm_test
    TEST_MYSQL_USERNAME: root
    TEST_MYSQL_PASSWORD:
    TEST_CACHE_ENABLE: true
  commands:
  - make test-mysql
  when:
    event:
    - push
    - pull_request

- name: test-mymysql
  pull: default
  image: golang:1.12
  depends_on:
    - test-mysql-utf8mb4-cache
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_MYSQL_HOST: mysql:3306
    TEST_MYSQL_DBNAME: xorm_test
    TEST_MYSQL_USERNAME: root
    TEST_MYSQL_PASSWORD:
    TEST_CACHE_ENABLE: false
  commands:
  - make test-mymysql
  when:
    event:
    - push
    - pull_request

- name: test-mymysql-cache
  pull: default
  image: golang:1.12
  depends_on:
    - test-mymysql
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_MYSQL_HOST: mysql:3306
    TEST_MYSQL_DBNAME: xorm_test
    TEST_MYSQL_USERNAME: root
    TEST_MYSQL_PASSWORD:
    TEST_CACHE_ENABLE: true
  commands:
  - make test-mymysql
  when:
    event:
    - push
    - pull_request

- name: test-postgres
  pull: default
  image: golang:1.12
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_PGSQL_HOST: pgsql
    TEST_PGSQL_DBNAME: xorm_test
    TEST_PGSQL_USERNAME: postgres
    TEST_PGSQL_PASSWORD: postgres
    TEST_CACHE_ENABLE: false
  commands:
  - make test-postgres
  when:
    event:
    - push
    - pull_request

- name: test-postgres-cache
  pull: default
  image: golang:1.12
  depends_on:
    - test-postgres
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_PGSQL_HOST: pgsql
    TEST_PGSQL_DBNAME: xorm_test
    TEST_PGSQL_USERNAME: postgres
    TEST_PGSQL_PASSWORD: postgres
    TEST_CACHE_ENABLE: true
  commands:
  - make test-postgres
  when:
    event:
    - push
    - pull_request

- name: test-postgres-schema
  pull: default
  image: golang:1.12
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_PGSQL_HOST: pgsql
    TEST_PGSQL_SCHEMA: xorm
    TEST_PGSQL_DBNAME: xorm_test
    TEST_PGSQL_USERNAME: postgres
    TEST_PGSQL_PASSWORD: postgres
    TEST_CACHE_ENABLE: false
    SCHEMA: xorm
  commands:
  - make test-postgres
  when:
    event:
    - push
    - pull_request

- name: test-postgres-schema-cache
  pull: default
  image: golang:1.12
  depends_on:
    - test-postgres-schema
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_PGSQL_HOST: pgsql
    TEST_PGSQL_SCHEMA: xorm
    TEST_PGSQL_DBNAME: xorm_test
    TEST_PGSQL_USERNAME: postgres
    TEST_PGSQL_PASSWORD: postgres
    TEST_CACHE_ENABLE: true
    SCHEMA: xorm
  commands:
  - make test-postgres
  when:
    event:
    - push
    - pull_request

- name: test-mssql
  pull: default
  image: golang:1.12
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_MSSQL_HOST: mssql
    TEST_MSSQL_DBNAME: xorm_test
    TEST_MSSQL_USERNAME: sa
    TEST_MSSQL_PASSWORD: "yourStrong(!)Password"
    TEST_CACHE_ENABLE: false
  commands:
  - make test-mssql
  when:
    event:
    - push
    - pull_request

- name: test-mssql-cache
  pull: default
  image: golang:1.12
  depends_on:
    - test-mssql
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_MSSQL_HOST: mssql
    TEST_MSSQL_DBNAME: xorm_test
    TEST_MSSQL_USERNAME: sa
    TEST_MSSQL_PASSWORD: "yourStrong(!)Password"
    TEST_CACHE_ENABLE: true
  commands:
  - make test-mssql
  when:
    event:
    - push
    - pull_request

- name: test-tidb
  pull: default
  image: golang:1.12
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_TIDB_HOST: "tidb:4000"
    TEST_TIDB_DBNAME: xorm_test
    TEST_TIDB_USERNAME: root
    TEST_TIDB_PASSWORD:
    TEST_CACHE_ENABLE: false
  commands:
  - make test-tidb
  when:
    event:
    - push
    - pull_request

- name: test-tidb-cache
  pull: default
  image: golang:1.12
  depends_on:
    - test-tidb
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
    TEST_TIDB_HOST: "tidb:4000"
    TEST_TIDB_DBNAME: xorm_test
    TEST_TIDB_USERNAME: root
    TEST_TIDB_PASSWORD:
    TEST_CACHE_ENABLE: true
  commands:
  - make test-tidb
  when:
    event:
    - push
    - pull_request

- name: merge_coverage
  pull: default
  image: golang:1.12
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn"
  depends_on:
  - test-vet
  - test-sqlite
  - test-sqlite-cache
  - test-mysql
  - test-mysql-cache
  - test-mysql-utf8mb4
  - test-mysql-utf8mb4-cache
  - test-mymysql
  - test-mymysql-cache
  - test-postgres
  - test-postgres-cache
  - test-postgres-schema
  - test-postgres-schema-cache
  - test-mssql
  - test-mssql-cache
  - test-tidb
  - test-tidb-cache
  commands:
  - make coverage
  when:
    event:
    - push
    - pull_request

services:

- name: mysql
  pull: default
  image: mysql:5.7
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_DATABASE: xorm_test
  when:
    event:
    - push
    - tag
    - pull_request

- name: pgsql
  pull: default
  image: postgres:9.5
  environment:
    POSTGRES_DB: xorm_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  when:
    event:
    - push
    - tag
    - pull_request

- name: mssql
  pull: default
  image: microsoft/mssql-server-linux:latest
  environment:
    ACCEPT_EULA: Y
    SA_PASSWORD: yourStrong(!)Password
    MSSQL_PID: Developer
  when:
    event:
    - push
    - tag
    - pull_request

- name: tidb
  pull: default
  image: pingcap/tidb:v3.0.3
  when:
    event:
    - push
    - tag
    - pull_request