name: test tidb
on: 
  push:
    branches:
      - master
  pull_request:

env:
  GOPROXY: https://goproxy.io,direct
  GOPATH: /go_path
  GOCACHE: /go_cache
  RUNNER_TOOL_CACHE: /toolcache # specify with your cache path

jobs:
  test-tidb:
    name: test tidb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - uses: https://gitea.com/actions/go-hashfiles@v0.0.1
        id: hash-go
        with:
          patterns: |
            go.mod
            go.sum
      - name: cache go
        id: cache-go
        uses: https://github.com/actions/cache@v3
        with:
          path: |
            /go_path
            /go_cache
          key: go_path-${{ steps.hash-go.outputs.hash }}
      - name: test tidb
        env:
          TEST_TIDB_HOST: "tidb:4000"
          TEST_TIDB_DBNAME: xorm_test
          TEST_TIDB_USERNAME: root
          TEST_TIDB_PASSWORD:
        run: make test-tidb

    services:
      tidb:
        image: pingcap/tidb:v3.0.3
        ports:
          - 4000:4000