name: test oracle
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: test oracle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: test oracle
        env:
          TEST_ORACLE_HOST: oracle:1521
          TEST_ORACLE_DBNAME: FREEPDB1
          TEST_ORACLE_USERNAME: system
          TEST_ORACLE_PASSWORD: oracle
        run: TEST_CACHE_ENABLE=false make test-oracle

    services:
      oracle:
        image: gvenzl/oracle-xe:latest
        env:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: system
          APP_USER_PASSWORD: oracle
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10